# Generated by Django 3.1.2 on 2020-10-28 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='MobileNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=11, null=True)),
                ('plan', models.CharField(max_length=100, null=True)),
                ('device', models.CharField(max_length=100, null=True)),
                ('insurance', models.CharField(max_length=200, null=True)),
                ('average_bill', models.FloatField(max_length=6)),
                ('data_allowance', models.FloatField(max_length=6, null=True)),
                ('spend_cap', models.CharField(choices=[('Non', 'None'), ('0', '0'), ('5', '5'), ('10', '10'), ('20', '20'), ('30', '30'), ('40', '40'), ('50', '50'), ('60', '60'), ('70', '70'), ('80', '80'), ('90', '90'), ('100', '100')], max_length=100, null=True)),
                ('data_usage_3m', models.FloatField(max_length=10)),
                ('data_gifted_3m', models.FloatField(max_length=10)),
                ('texts_sent_3m', models.IntegerField(null=True)),
                ('call_mins', models.IntegerField(null=True)),
                ('sms_sent', models.IntegerField(null=True)),
                ('contract_start', models.DateField()),
                ('upgrade_date', models.DateField()),
                ('contract_length_months', models.CharField(choices=[('1', '1'), ('12', '12'), ('18', '18'), ('24', '24')], max_length=10, null=True)),
                ('annual_upgrade_fee', models.CharField(choices=[('200', '200'), ('100', '100'), ('0', '0')], max_length=10, null=True)),
                ('early_upgrade_fee', models.FloatField(null=True)),
                ('friends_and_family', models.BooleanField(null=True)),
                ('perk', models.BooleanField(null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='firstname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='lastname',
            new_name='last_name',
        ),
    ]
