# Generated by Django 3.1.2 on 2020-10-28 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201028_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobilenumber',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.customer'),
        ),
    ]
