# Generated by Django 3.1.2 on 2020-10-28 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20201028_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobilenumber',
            name='user',
            field=models.CharField(max_length=11, null=True),
        ),
    ]
