# Generated by Django 3.1.2 on 2020-10-28 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_mobilenumber_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobilenumber',
            name='annual_upgrade_fee',
            field=models.CharField(choices=[('NA', 'NA'), ('200', '200'), ('100', '100'), ('0', '0')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='mobilenumber',
            name='spend_cap',
            field=models.CharField(choices=[('None', 'None'), ('0', '0'), ('5', '5'), ('10', '10'), ('20', '20'), ('30', '30'), ('40', '40'), ('50', '50'), ('60', '60'), ('70', '70'), ('80', '80'), ('90', '90'), ('100', '100')], max_length=100, null=True),
        ),
    ]
