# Generated by Django 3.1.2 on 2020-10-29 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20201029_1112'),
    ]

    operations = [
        migrations.CreateModel(
            name='Handsets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacture', models.CharField(choices=[('Apple', 'Apple'), ('Samsung', 'Samsung'), ('Huawei', 'Huawei'), ('Sony', 'Sony'), ('Google', 'Google'), ('Oppo', 'Oppo'), ('Motorola', 'Motorola')], max_length=30, null=True)),
                ('model', models.CharField(max_length=100, null=True)),
                ('storage', models.IntegerField(null=True)),
                ('cost_price', models.FloatField(max_length=10)),
                ('product_code', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HandsetTariffs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='SimOnlyTariffs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_length', models.CharField(choices=[('1', '1'), ('12', '12'), ('18', '18'), ('24', '24')], max_length=10, null=True)),
                ('plan_name', models.CharField(max_length=100, null=True)),
                ('mrc', models.IntegerField(null=True)),
                ('data_allowance', models.CharField(choices=[('0.25', '0.25'), ('1', '1'), ('3', '3'), ('20', '20'), ('60', '60'), ('100', '100'), ('200', '200'), ('1000', '1000')], max_length=10, null=True)),
                ('plan_type', models.CharField(choices=[('Essential', 'Essential'), ('Smart', 'Smart')], max_length=10, null=True)),
                ('tariff_code', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
