# Generated by Django 3.1.2 on 2020-10-29 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_handsets_handsettariffs_simonlytariffs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simonlytariffs',
            name='data_allowance',
            field=models.CharField(choices=[('0.25', '0.25'), ('1', '1'), ('3', '3'), ('20', '20'), ('60', '60'), ('100', '100'), ('200', '200'), ('10000', '10000')], max_length=10, null=True),
        ),
    ]
