# Generated by Django 3.1.2 on 2020-10-29 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20201029_2105'),
    ]

    operations = [
        migrations.CreateModel(
            name='BTBroadband',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_start', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='EEBroadband',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_start', models.DateField()),
            ],
        ),
    ]
