# Generated by Django 3.1.2 on 2020-10-30 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20201030_2056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simonlyorder',
            name='tariff',
        ),
        migrations.AddField(
            model_name='simonlyorder',
            name='items',
            field=models.ManyToManyField(to='main.SimOnlyOrderItem'),
        ),
    ]
