# Generated by Django 3.1.2 on 2020-10-30 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20201030_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='simonlytariffs',
            name='upfront',
            field=models.IntegerField(null=True),
        ),
    ]
