# Generated by Django 3.1.2 on 2020-10-30 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_simonlytariffs_upfront'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simonlytariffs',
            name='mrc',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='simonlytariffs',
            name='upfront',
            field=models.FloatField(null=True),
        ),
    ]
