# Generated by Django 3.1.2 on 2020-10-30 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20201030_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simonlytariffs',
            name='mrc',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='simonlytariffs',
            name='upfront',
            field=models.IntegerField(null=True),
        ),
    ]
