# Generated by Django 3.1.2 on 2020-11-06 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20201030_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='addons',
            name='spend_cap',
            field=models.CharField(choices=[('None', 'None'), ('0', '0'), ('5', '5'), ('10', '10'), ('20', '20'), ('30', '30'), ('40', '40'), ('50', '50'), ('60', '60'), ('70', '70'), ('80', '80'), ('90', '90'), ('100', '100')], max_length=100, null=True),
        ),
    ]
