# Generated by Django 3.1.2 on 2020-11-07 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_addons_spend_cap'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpendCaps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cap_amount', models.CharField(choices=[('None', 'None'), ('0', '0'), ('5', '5'), ('10', '10'), ('20', '20'), ('30', '30'), ('40', '40'), ('50', '50'), ('60', '60'), ('70', '70'), ('80', '80'), ('90', '90'), ('100', '100')], max_length=100, null=True)),
                ('cap_name', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='mobilenumber',
            name='insurance_type',
            field=models.CharField(choices=[('Full Cover £14 ', 'Full Cover £14'), ('Damage Cover £12.32', 'Damage Cover £12.32'), ('Full Cover £12.32', 'Full Cover £12.32'), ('Damage Cover 7.84', 'Damage Cover 7.84'), ('None', 'None')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='mobilenumber',
            name='insurance',
            field=models.BooleanField(default=False),
        ),
    ]
