# Generated by Django 3.1.2 on 2020-11-07 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20201107_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='add_lines_availible',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=200, null=True),
        ),
    ]
