# Generated by Django 3.1.2 on 2020-11-07 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_customer_add_lines_availible'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='add_lines_availible',
            new_name='add_lines_available',
        ),
    ]
