# Generated by Django 3.1.2 on 2020-11-08 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_auto_20201107_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='spendcaps',
            name='mrc',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='spendcaps',
            name='upfront',
            field=models.IntegerField(null=True),
        ),
    ]
