# Generated by Django 3.1.2 on 2020-11-08 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_auto_20201108_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='spendcaps',
            name='cap_code',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
