# Generated by Django 3.1.2 on 2020-11-09 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_simonlyorderitem_cap'),
    ]

    operations = [
        migrations.AddField(
            model_name='simonlyorder',
            name='tariff',
            field=models.ManyToManyField(null=True, to='main.SimOnlyTariffs'),
        ),
    ]
