# Generated by Django 3.1.2 on 2020-11-09 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_simonlyorder_tariff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simonlyorder',
            name='tariff',
        ),
        migrations.AddField(
            model_name='simonlyorder',
            name='tariff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.simonlytariffs'),
        ),
    ]
