# Generated by Django 3.1.2 on 2020-11-09 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_auto_20201109_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simonlyorder',
            name='tariff',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.simonlytariffs'),
        ),
    ]
