# Generated by Django 3.1.2 on 2020-11-09 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_simonlyorder_cap'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insurance_name', models.CharField(choices=[('Full Cover £14 ', 'Full Cover £14'), ('Damage Cover £12.32', 'Damage Cover £12.32'), ('Full Cover £12.32', 'Full Cover £12.32'), ('Damage Cover 7.84', 'Damage Cover 7.84'), ('None', 'None')], max_length=200, null=True)),
                ('upfront', models.IntegerField(null=True)),
                ('mrc', models.IntegerField(null=True)),
                ('excess_fee', models.CharField(choices=[('120', '120'), ('100', '100')], max_length=200, null=True)),
                ('ins_code', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='simonlyorder',
            name='items',
        ),
    ]
