# Generated by Django 3.1.2 on 2020-11-09 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_auto_20201109_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurance',
            name='mrc',
            field=models.FloatField(null=True),
        ),
    ]
