# Generated by Django 3.1.2 on 2020-11-09 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_auto_20201109_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobilenumber',
            name='insurance_option',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.insurance'),
        ),
    ]
