# Generated by Django 3.1.2 on 2020-11-09 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_mobilenumber_insurance_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='simonlyorder',
            name='existing_insurance',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.insurance'),
        ),
    ]
