# Generated by Django 3.1.2 on 2020-11-10 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_simonlyorder_existing_insurance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simonlytariffs',
            name='upfront',
            field=models.FloatField(null=True),
        ),
    ]
