# Generated by Django 3.1.2 on 2020-11-10 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_auto_20201110_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simonlytariffs',
            name='mrc',
            field=models.FloatField(null=True),
        ),
    ]
