# Generated by Django 3.1.2 on 2020-11-10 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_auto_20201110_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurance',
            name='insurance_name',
            field=models.CharField(choices=[('Full Cover £14 ', 'Full Cover £14'), ('Damage Cover £12.32', 'Damage Cover £12.32'), ('Full Cover £12.32', 'Full Cover £12.32'), ('Damage Cover 7.84', 'Damage Cover 7.84'), ('No Insurance', 'No Insurance')], max_length=200, null=True),
        ),
    ]
