# Generated by Django 3.1.2 on 2020-11-10 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_auto_20201110_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='simonlyorder',
            name='postcode_validated',
            field=models.BooleanField(null=True),
        ),
    ]
