# Generated by Django 3.1.2 on 2020-11-10 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_simonlyorder_postcode_validated'),
    ]

    operations = [
        migrations.AddField(
            model_name='simonlyorder',
            name='mob_validated',
            field=models.BooleanField(null=True),
        ),
    ]
