# Generated by Django 3.1.2 on 2020-11-12 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_simonlyorder_mob_validated'),
    ]

    operations = [
        migrations.AddField(
            model_name='simonlyorder',
            name='otp',
            field=models.IntegerField(null=True),
        ),
    ]
