# Generated by Django 3.1.2 on 2020-11-12 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_simonlyorder_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='simonlyorder',
            name='otp_validated',
            field=models.BooleanField(null=True),
        ),
    ]
