# Generated by Django 3.1.2 on 2020-11-18 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_mobilenumber_contract_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobilenumber',
            name='annual_upgrade',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
