# Generated by Django 3.1.2 on 2020-11-18 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_mobilenumber_mrc'),
    ]

    operations = [
        migrations.AddField(
            model_name='handsets',
            name='mrc',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='handsets',
            name='upfront',
            field=models.FloatField(null=True),
        ),
    ]
