# Generated by Django 3.1.2 on 2020-11-21 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0047_auto_20201118_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handsets',
            name='tariffs_availible',
            field=models.ManyToManyField(to='main.HandsetTariffs'),
        ),
        migrations.CreateModel(
            name='HandsetOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=10, null=True)),
                ('is_ordered', models.BooleanField(default=False)),
                ('cap', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.spendcaps')),
                ('cus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.customer')),
                ('handset', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.handsets')),
                ('insurance', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.insurance')),
                ('tariff', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.simonlytariffs')),
            ],
        ),
    ]
