# Generated by Django 3.1.2 on 2020-11-22 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0049_handsets_colour'),
    ]

    operations = [
        migrations.AddField(
            model_name='handsets',
            name='speed_type',
            field=models.CharField(choices=[('5G', '5G'), ('4G', '4G')], max_length=30, null=True),
        ),
    ]
