# Generated by Django 3.1.2 on 2020-11-24 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0050_handsets_speed_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='handsetorder',
            old_name='tariff',
            new_name='handset_tariff',
        ),
    ]
