# Generated by Django 3.1.2 on 2020-11-24 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0052_handsetorder_upfront'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handsetorder',
            name='handset_tariff',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.handsettariffs'),
        ),
    ]
