# Generated by Django 3.1.2 on 2020-11-24 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0053_auto_20201124_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handsetorder',
            name='upfront',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.CreateModel(
            name='HandsetStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imei', models.CharField(max_length=15, null=True)),
                ('handset', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.handsets')),
            ],
        ),
    ]
