# Generated by Django 3.1.2 on 2020-11-24 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0054_auto_20201124_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handsetstock',
            name='handset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.handsets'),
        ),
    ]
