# Generated by Django 3.1.2 on 2020-11-25 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0055_auto_20201124_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='handsets',
            name='insurance_available',
            field=models.ManyToManyField(to='main.Insurance'),
        ),
    ]
