# Generated by Django 3.1.2 on 2020-11-25 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0056_handsets_insurance_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='handsetorder',
            name='early_upgrade_fee',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
