# Generated by Django 3.1.2 on 2020-11-25 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0057_handsetorder_early_upgrade_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='handsetorder',
            name='annual_upgrade_fee',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
