# Generated by Django 3.1.2 on 2020-11-28 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0058_handsetorder_annual_upgrade_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='handsetorder',
            name='friends_and_family',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
