# Generated by Django 3.1.2 on 2020-11-28 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0059_handsetorder_friends_and_family'),
    ]

    operations = [
        migrations.AddField(
            model_name='simonlyorder',
            name='friends_and_family',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
