# Generated by Django 3.1.2 on 2020-11-28 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0061_simonlyorder_handset_credit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simonlyorder',
            name='handset_credit',
        ),
        migrations.AddField(
            model_name='handsetorder',
            name='handset_credit',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
