# Generated by Django 3.1.2 on 2020-11-30 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0062_auto_20201128_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='handsetorder',
            name='date_ordered',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='handsetorder',
            name='mob_validated',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='handsetorder',
            name='otp',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='handsetorder',
            name='otp_validated',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='handsetorder',
            name='postcode_validated',
            field=models.BooleanField(null=True),
        ),
    ]
