# Generated by Django 3.1.2 on 2020-12-19 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0063_auto_20201130_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='handsetorder',
            name='one_hundred_day_promo',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
