# Generated by Django 3.1.2 on 2020-12-19 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0064_handsetorder_one_hundred_day_promo'),
    ]

    operations = [
        migrations.AddField(
            model_name='handsetorder',
            name='ctn',
            field=models.CharField(max_length=11, null=True),
        ),
    ]
