# Generated by Django 3.1.2 on 2020-12-20 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0066_auto_20201220_1932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='handsetorder',
            name='annual_upgrade_fee',
        ),
        migrations.AddField(
            model_name='handsetorder',
            name='contract_length',
            field=models.CharField(default='24', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='handsetorder',
            name='contract_type',
            field=models.CharField(default='EE Handset Sale', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='simonlyorder',
            name='contract_length',
            field=models.CharField(choices=[('1', '1'), ('12', '12'), ('18', '18'), ('24', '24')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='simonlyorder',
            name='contract_type',
            field=models.CharField(default='EE Sim-Only Sale', max_length=30, null=True),
        ),
    ]
