# Generated by Django 3.1.2 on 2020-12-20 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0067_auto_20201220_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='simonlyorder',
            name='ctn',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='handsetorder',
            name='contract_length',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='simonlyorder',
            name='contract_type',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
