# Generated by Django 3.1.2 on 2020-12-20 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0068_auto_20201220_2101'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SimOnlyOrderItem',
        ),
    ]
