# Generated by Django 3.1.2 on 2020-12-24 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0070_delete_addons'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='btbroadband',
            options={'verbose_name_plural': 'BT Broadband'},
        ),
        migrations.AlterModelOptions(
            name='eebroadband',
            options={'verbose_name_plural': 'EE Broadband'},
        ),
        migrations.AlterModelOptions(
            name='handsets',
            options={'ordering': ['manufacture', 'model'], 'verbose_name_plural': 'Handsets'},
        ),
        migrations.AlterModelOptions(
            name='handsetstock',
            options={'verbose_name_plural': 'Handset Stock'},
        ),
        migrations.AlterModelOptions(
            name='handsettariffs',
            options={'ordering': ['tariff_code'], 'verbose_name_plural': 'Handset Tariffs'},
        ),
        migrations.AlterModelOptions(
            name='insurance',
            options={'verbose_name_plural': 'Insurance'},
        ),
        migrations.AlterModelOptions(
            name='simonlytariffs',
            options={'verbose_name_plural': 'Sim Only Tariffs'},
        ),
        migrations.AlterModelOptions(
            name='spendcaps',
            options={'verbose_name_plural': 'Spend Caps'},
        ),
        migrations.AddField(
            model_name='handsetorder',
            name='handset_imei',
            field=models.IntegerField(max_length=15, null=True),
        ),
    ]
