# Generated by Django 3.1.2 on 2020-12-24 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0071_auto_20201224_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handsetorder',
            name='handset_imei',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
