# Generated by Django 3.1.2 on 2021-01-03 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0072_auto_20201224_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='handsetorder',
            name='handset_imei_validated',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='handsetorder',
            name='mob_validated',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='handsetorder',
            name='otp_validated',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='handsetorder',
            name='postcode_validated',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
