# Generated by Django 3.1.2 on 2021-01-03 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0073_auto_20210103_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handsetorder',
            name='handset_imei_validated',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='handsetorder',
            name='mob_validated',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='handsetorder',
            name='otp_validated',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='handsetorder',
            name='postcode_validated',
            field=models.BooleanField(null=True),
        ),
    ]
