# Generated by Django 3.1.2 on 2021-01-04 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0074_auto_20210103_2104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mobilenumber',
            name='insurance_type',
        ),
    ]
