# Generated by Django 3.1.2 on 2021-01-20 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0075_remove_mobilenumber_insurance_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handsets',
            name='manufacture',
            field=models.CharField(choices=[('Apple', 'Apple'), ('Samsung', 'Samsung')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='simonlytariffs',
            name='plan_type',
            field=models.CharField(choices=[('Standard', 'Standard')], max_length=10, null=True),
        ),
    ]
