# Generated by Django 3.1.2 on 2021-01-20 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0076_auto_20210120_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handsettariffs',
            name='plan_type',
            field=models.CharField(choices=[('Essential', 'Essential')], max_length=10, null=True),
        ),
    ]
