# Generated by Django 3.1.2 on 2021-01-20 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0077_auto_20210120_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handsets',
            name='manufacture',
            field=models.CharField(choices=[('Pear', 'Pear'), ('Soulsung', 'Soulsung')], max_length=30, null=True),
        ),
    ]
