# Generated by Django 3.1.2 on 2021-01-20 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0078_auto_20210120_2102'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BTBroadband',
        ),
        migrations.DeleteModel(
            name='EEBroadband',
        ),
    ]
