# Generated by Django 3.1.2 on 2021-01-21 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0079_auto_20210120_2153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mobilenumber',
            name='upgrade_date',
        ),
        migrations.AlterField(
            model_name='simonlytariffs',
            name='data_allowance',
            field=models.CharField(choices=[('0.25', '0.25'), ('1', '1'), ('3', '3'), ('20', '20'), ('60', '60'), ('100', '100'), ('200', '200'), ('1000', '1000')], max_length=10, null=True),
        ),
    ]
